apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
data:
  pacrd.yaml: |
    spinnakerServices:
      front50: http://spin-front50.spinnaker:8080
      orca: http://spin-orca.spinnaker:8083
