# permissions to do edit pipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-editor-role
rules:
- apiGroups:
  - pacrd.armory.spinnaker.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pacrd.armory.spinnaker.io
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
