
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - patch
- apiGroups:
  - pacrd.armory.spinnaker.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pacrd.armory.spinnaker.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pacrd.armory.spinnaker.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pacrd.armory.spinnaker.io
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
