apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Application
metadata:
  name: nicotest
spec:
  email: ***REMOVED***
  user: ***REMOVED***
  description: wondering why front50 doesn't work as expected
