apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Application
metadata:
  name: nicotest
spec:
  email: fernando.freire@armory.io
  user: ffreire
  description: wondering why front50 doesn't work as expected
