apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: deploy-manifest-test
spec:
  description: Foo bar baz
  application: &app-name deploy-manifest-ds
  parameterConfig:
    - name: example_var
      default: "false"
      hasOptions: false
      label: example_var
      pinned: false
      required: true
  stages:
    - type: bakeManifest
      properties:
        refId: "1"
        name: Bake Some Bread
        evaluateOverrideExpressions: false
        outputName: bread
        expectedArtifacts: []
        inputArtifacts: []
        templateRenderer: HELM2
        namespace: this2
        comments: My comment
        stageEnabled:
          type: expression
          expression: "true == false"
    - type: wait
      properties:
        refId: "2"
        requisiteStageRefIds:
          - "1"
        name: waiting for the bread
        waitTime: 304
    - type: manualJudgment
      properties:
        refId: "3"
        name: bread ready, do you want some?
        requisiteStageRefIds:
          - "2"
        failPipeline: true
        continuePipeline: false
        completeOtherBranchesThenFail: false
        instructions: "Do you want to promote canary to Production?"
        judgmentInputs:
          - value: No promote
          - value: Promote
    - type: webhook
      properties:
        name: Please work
        refId: "4"
        requisiteStageRefIds:
          - "3"
        cancelEndpoint: cancellation url
        cancelMethod: POST
        #        cancelPayload: |
        #          cancelation: payload
        canceledStatuses: CANCELED, CANCEL
        customHeaders: |
          customheader: customvalue
          customheader2: customalue2
        method: POST
        payload: |
          {
            "deployment": {
              "revision": "v1.0.0",
              "user": "${parameterValues['user']}",
              "description": "${dasdasd['description']}"
            }
          }
        progressJsonPath: $.buildInfo.status
        failFastStatusCodes: [ 404, 418 ]
        retryStatusCodes: [ 404, 418 ]
        statusJsonPath: $.buildInfo.status
        statusUrlResolution: webhookResponse
        statusUrlJsonPath: http://test
        successStatuses: SUCCESS, OK
        terminalStatuses: TERMINAL, FINISHED
        url: webhook url
        waitBeforeMonitor: "1"
        waitForCompletion: true
        comments: This is a test for weekhooks
        stageEnabled:
          type: expression
          expression: "true == false"
    - type: pipeline
      properties:
        refId: "5"
        requisiteStageRefIds:
          - "4"
        name: execute second pipeline
        failPipeline: true
        pipeline: 3dc1f6d5-842f-4862-bbb1-ca40904d6936
        waitForCompletion: true