# file: pipeline.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: myapplicationpipeline
spec:
  description: Delivery pipeline for the MyApplicationName service.
  application: myapplicationname
  stages:
    - name: Bake Application
      refId: "1"
      bakeManifest:
        # ...
    # Note: In `v0.1.0` you are required to sepcify _both_ `type: BakeManifest`
    #       as well as place options under a `bakeManifest` key. Consult the
    #       "Current Limitations" section above for more information.
    - type: BakeManifest
      bakeManifest:
        name: Bake Application
        evaluateOverrideExpressions: false
        outputName: myapplicationname
        templateRenderer: helm2
        refId: "1"
    - type: ManualJudgment
      manualJudgment:
        name: Bake Successful?
        comments: Was the bake successful?
        failPipeline: true
        instructions: Check to see if the helm template was baked correctly
        refId: "2"
        requisiteStageRefIds: [ "1" ]
