apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: simpleminds
spec:
  description: Foo bar baz
  application: woohoo
  stages:
    - type: BakeManifest
      bakeManifest:
        name: Name isn't being set for some reason.
        evaluateOverrideExpressions: false
        outputName: bread
        expectedArtifacts: []
        inputArtifacts: []
        templateRenderer: helm2
        refId: "1"
    - type: ManualJudgment
      manualJudgment:
        name: Don't You, Forget About Me
        comments: Hey, hey, hey, heyyyyy
        failPipeline: false
        instructions: DON'T PANIC, COVID-19 UP IN YOUR BUSINESS
        judgmentInputs:  # No, this key is not spelled incorrectly
          - value: I'll never forget you, Dawson
          - value: Don't be such a snob, Dawson!
        # TODO this should really be calculated by the controller
        refId: "2"
        requisiteStageRefIds: [ "1" ]
    #- type: findArtifactFromResource
      #name: Find the Bread
      #account: "hlp-eks-spe-navnonprod-pdx"
      #app: woohoo
      #cloudProvider: kubernetes
      #location: entitlements
      #manifestName: "deployment eks-spe-entitlements-***REMOVED***"
      #mode: static
