# file: pipeline.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: pacrd-manualjudgment-samples
spec:
  description: Manual Judgment pipeline sample
  application: &app-name pacrd-pipeline-stages-samples
  stages:
    - type: manualJudgment
      properties:
        name: Manual example
        refId: "1"
        failPipeline: true
        instructions: Check if this stage works