#Webhook
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: pacrd-webhook-samples
spec:
  description: Samples for Webhooks
  application:  &app-name pacrd-pipeline-stages-samples
  stages:
    - type: webhook
      properties:
        name: Waiting for completion from webhook repsonse
        refId: "1"
        cancelEndpoint: cancellation url
        cancelMethod: POST
        cancelPayload: |
          {
            "cancelation": "payload"
          }
        canceledStatuses: CANCELED, CANCEL
        customHeaders: |
          {
            "customheader": "customvalue",
            "customheader2": "customalue2"
          }
        method: POST
        payload: |
          {
            "test": payloadtest,
            "statuscode": 200
          }
        progressJsonPath: $.buildInfo.status
        failFastStatusCodes: [ 404, 418 ]
        retryStatusCodes: [ 404, 418 ]
        statusJsonPath: $.buildInfo.status
        statusUrlResolution: webhookResponse
        statusUrlJsonPath: http://test
        successStatuses: SUCCESS, OK
        terminalStatuses: TERMINAL, FINISHED
        url: webhook url
        waitBeforeMonitor: "1"
        waitForCompletion: true
        comments: This is a test for weekhooks
        signalCancellation: true