# file: pipeline.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: pacrd-checkpreconditions-samples
spec:
  description: Check Preconditions example
  application: &app-name pacrd-pipeline-stages-samples
  parameterConfig:
    - name: canary_deploy
      default: "false"
      hasOptions: false
      label: canary_deploy
      pinned: false
      required: true
  stages:
    - type: checkPreconditions
      properties:
        name: Check Canary
        refId: "1"
        preconditions:
          - type: expression
            context:
              expression: parameters[  \"canary_deploy\"  ]  == \"true\"
              failureMessage: "this execution failed"
            failPipeline: true
