### Find artifacts from resource
# file: pipeline-stage-findartifactsfromresource.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: pacrd-findartifactsfromresource-samples
spec:
  description: Find Artifacts From Resource pipeline sample
  application: &app-name pacrd-pipeline-stages-samples
  stages:
    - type: findArtifactsFromResource
      properties:
        refId: "1"
        name: Find Baseline
        account: kubernetes
        app: *app-name
        cloudProvider: kubernetes
        location: spinnaker
        manifestName: deployment something
        mode: static