### Bake Manifest
# file: pipeline-stage-bakemanifest.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: pacrd-bakemanifest-samples
spec:
  description: Bake Manifest pipeline sample
  application:  &app-name pacrd-pipeline-stages-samples
  stages:
    - type: bakeManifest
      properties:
        name: Bake Application
        refId: "1"
        outputName: *app-name
        templateRenderer: helm2