#DeleteManifest
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: pacrd-undorollout-samples
spec:
  description: Samples for undorollout
  application: &app-name pacrd-pipeline-stages-samples
  stages:
    - type: manualJudgment
      properties:
        name: Should we start?
        refId: "1"
        failPipeline: true
        instructions: Check if this stage works
    - type: undoRolloutManifest
      properties:
        name: Static target
        refId: "2"
        requisiteStageRefIds: [ "1" ]
        account: kubernetes
        app: *app-name
        cloudProvider: kubernetes
        location: &location ffreire
        mode: static
        kind: apiService
        targetName: testingName
        numRevisionsBack: 1
